<?php
    $serv="localhost";
    //$uname="u189960358_kud";
    $uname="kudin_kud";
    $pwd="KUDdwd@123";
    $db="kudin_kud";
    $conn=mysqli_connect($serv,$uname,$pwd);
    mysqli_select_db($conn,$db);
?>