<?php
    $serv="localhost";
    //$uname="kudin_kudresult";
    $uname="kudin_external";
    $pwd="external@kud";
    $db="kudin_external";
    $conn=mysqli_connect($serv,$uname,$pwd);
    mysqli_select_db($conn,$db);
?>